#ifndef _MATRIX_H_
#define _MATRIX_H_

#include  <iostream>
#include  <vector>

class Matrix{
  protected:

    // Protected attributes
    std::vector<std::vector<double>> data;
    unsigned int rows;
    unsigned int cols;

    // Protected constructors
    Matrix();
    // Required for the derived class constructors

  public:

    // Public constructors
    Matrix(const Matrix& other);
    // Instanciates a Matrix from a copy constructor

    Matrix(std::vector<std::vector<double>>& inputData);
    // Instanciates a Matrix from a two dimension vector of double

    Matrix(int numberOfRows,int numberOfCols);
    // Instanciates a Matrix with random positive numbers

    Matrix(int numberOfRows,int numberOfCols, double minLimit, double maxLimit);
    // Instanciates a Matrix with random positive numbers 
    // between the arguments minLimit and maxLimit

    Matrix(int numberOfRows, int numberOfCols, std::string elements);
    // Instanciates a Matrix using the data from a string

    // Public methods
    unsigned int GetRows() const;
    // Returns the number of rows

    unsigned int GetCols() const;
    // Returns the number of cols

    Matrix operator=(const Matrix& other) = delete;
    // Prevents Matrix data from being changed by the assignment operator

    virtual bool IsEqual(const Matrix& other) const;
    // Compares the content between two Matrix

    virtual bool operator==(const Matrix& other) const;
    // Compares the content between two Matrix

    virtual bool IsDifferent(const Matrix& other) const;
    // Compares the content between two Matrix
    
    virtual bool operator!=(const Matrix& other) const;
    // Compares the content between two Matrix

    double operator()(const unsigned int& I, const unsigned int& J) const;
    // Returns the Matrix's element indexed by row I and col J

    virtual Matrix Add(const Matrix& other) const;
    // Returns the result of a addition matrix operation

    virtual Matrix operator+(const Matrix& other) const;
    // Returns the result of a addition matrix operation

    virtual Matrix Subtract(const Matrix& other) const;
    // Returns the result of a subtraction matrix operation

    virtual Matrix operator-(const Matrix& other) const;
    // Returns the result of a subtraction matrix operation

    virtual Matrix Multiply(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    virtual Matrix operator*(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    virtual Matrix Multiply(const double& scalar) const;
    // Returns the result of a matrix scalar multiplication

    virtual Matrix operator*(const double& scalar) const;
    // Returns the result of a matrix scalar multiplication

    friend Matrix operator*(const double& scalar, const Matrix& matrix);
    // Returns the result of a matrix scalar multiplication

    virtual Matrix Divide(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    virtual Matrix operator/(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    void Print() const;
    // Prints the Matrix's content

    bool IsNull() const;
    // Checks if a matrix is Null/Zero

    bool IsDiagonal() const;
    // Checks if a matrix is Diagonal

    bool IsTriangular() const;
    // Checks if a matrix is Triangular

    bool IsSymmetric() const;
    // Checks if a matrix is Symmetric

    virtual double Determinant() const;
    // Calculates the matrix's Determinant

    Matrix SubMatrix(int i, int j) const;
    // Returns a SubMatrix generated by removing the ith row and jth column

    Matrix Transpose() const;
    // Returns the Transpose of the matrix

    Matrix Inverse() const;
    // Returns the Inverse of the matrix

    void LU(Matrix& L, Matrix& U, Matrix& P) const;
    // LU Decomposition with partial pivoting (PA = LU)

    virtual ~Matrix();
};

  std::ostream& operator<<(std::ostream& os, const Matrix& matrix);

class IdentityMatrix : public Matrix{
  public:

    // Public constructors
    IdentityMatrix(int Order);
    // Instanciates a IdentityMatrix with order specified by the variable Order

    IdentityMatrix(const IdentityMatrix& other);
    // Instanciates a IdentityMatrix  from a copy constructor

    virtual Matrix Multiply(const Matrix& other) const override;
    // Optimizes the computation of a multiplication matrix operation

    double Determinant() const override;
    // Optimizes the determinant's calculus

    ~IdentityMatrix();
};

class VandermondeMatrix : public Matrix{
  public:

    // Public constructors
    VandermondeMatrix(std::vector<double>& inputData, int numberOfCols);
    // Instanciates a VandermondeMatrix with inputData's size of rows and cols specified by numberOfCols.

    VandermondeMatrix(std::vector<double>& inputData);
    // Instanciates a square VandermondeMatrix with order specified by inputData's size.

    double Determinant() const override;
    // Returns the matrix's determinant through optimized calculation methods.

    ~VandermondeMatrix();
};


#endif // _MATRIX_H_S