#ifndef _MATRIX_H_
#define _MATRIX_H_

#include  <iostream>
#include  <vector>

class Matrix{
  protected:

    // Protected attributes
    std::vector<std::vector<double>> data;
    unsigned int rows;
    unsigned int cols;

    // Protected constructors
    Matrix();
    // Required for the derived class constructors

  public:

    // Public constructors
    Matrix(const Matrix& other);
    // Instantiates a Matrix from a copy constructor

    Matrix(std::vector<std::vector<double>>& inputData);
    // Instantiates a Matrix from a two dimension vector of double

    Matrix(int numberOfRows, int numberOfCols);
    // Instantiates a Matrix with random positive numbers

    Matrix(int numberOfRows, int numberOfCols, double minLimit, double maxLimit);
    // Instantiates a Matrix with random positive numbers
    // between the arguments minLimit and maxLimit

    Matrix(int numberOfRows, int numberOfCols, std::string elements);
    // Instantiates a Matrix using the data from a string

    Matrix(int numberOfRows, int numberOfCols, double value);
    // Instantiates a Matrix where each element is a copy of 'value'

    // Public methods
    unsigned int getRows() const;
    // Returns the number of rows

    unsigned int getCols() const;
    // Returns the number of cols

    virtual bool isEqual(const Matrix& other) const;
    // Compares the content between two Matrix

    virtual bool operator==(const Matrix& other) const;
    // Compares the content between two Matrix

    virtual bool isDifferent(const Matrix& other) const;
    // Compares the content between two Matrix
    
    virtual bool operator!=(const Matrix& other) const;
    // Compares the content between two Matrix

    double operator()(const unsigned int& I, const unsigned int& J) const;
    // Returns the Matrix's element indexed by row I and col J

    virtual Matrix add(const Matrix& other) const;
    // Returns the result of a addition matrix operation

    virtual Matrix operator+(const Matrix& other) const;
    // Returns the result of a addition matrix operation

    virtual Matrix subtract(const Matrix& other) const;
    // Returns the result of a subtraction matrix operation

    virtual Matrix operator-(const Matrix& other) const;
    // Returns the result of a subtraction matrix operation

    virtual Matrix multiply(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    virtual Matrix operator*(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    virtual Matrix multiply(const double& scalar) const;
    // Returns the result of a matrix scalar multiplication

    virtual Matrix operator*(const double& scalar) const;
    // Returns the result of a matrix scalar multiplication

    friend Matrix operator*(const double& scalar, const Matrix& matrix);
    // Returns the result of a matrix scalar multiplication

    virtual Matrix divide(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    virtual Matrix operator/(const Matrix& other) const;
    // Returns the result of a multiplication matrix operation

    bool isNull() const;
    // Checks if a matrix is Null/Zero

    bool isDiagonal() const;
    // Checks if a matrix is Diagonal

    bool isTriangular() const;
    // Checks if a matrix is Triangular

    bool isSymmetric() const;
    // Checks if a matrix is Symmetric

    virtual double determinant() const;
    // Calculates the matrix's Determinant

    Matrix subMatrix(int i, int j) const;
    // Returns a SubMatrix generated by removing the ith row and jth column

    virtual Matrix transpose() const;
    // Returns the Transpose of the matrix

    virtual Matrix inverse() const;
    // Returns the Inverse of the matrix

    void print() const;
    // Prints the Matrix's content

    virtual ~Matrix();
};

  std::ostream& operator<<(std::ostream& os, const Matrix& matrix);

class IdentityMatrix : public Matrix{
  public:

    // Public constructors
    IdentityMatrix(int Order);
    // Instanciates a IdentityMatrix with order specified by the variable Order

    IdentityMatrix(const IdentityMatrix& other);
    // Instanciates a IdentityMatrix  from a copy constructor

    virtual Matrix multiply(const Matrix& other) const override;
    // Optimizes the computation of a multiplication matrix operation

    double determinant() const override;
    // Optimizes the determinant's calculus

    Matrix transpose() const override;
    // Optimizes the Transpose calculus

    Matrix inverse() const override;
    // Optimizes the Inverse calculus

    ~IdentityMatrix();
};

class VandermondeMatrix : public Matrix{
  public:

    // Public constructors
    VandermondeMatrix(std::vector<double>& inputData, int numberOfCols);
    // Instanciates a VandermondeMatrix with inputData's size of rows and cols specified by numberOfCols.

    VandermondeMatrix(std::vector<double>& inputData);
    // Instanciates a square VandermondeMatrix with order specified by inputData's size.

    double determinant() const override;
    // Returns the matrix's determinant through optimized calculation methods.

    ~VandermondeMatrix();
};

#endif // _MATRIX_H_
